name: katelynpriceart
favicon: null
layout_spectrum: 0.49931
typography_spectrum: 0.51794
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f9ffff'
    - '#ffbd00'
    - '#654248'
    - '#da14fc'
  brandStrength: 0.5061409450136125
  lightness: 0.8468621396459639
  saturation: 0.8002835817169398
  rhythmicContrast: 0.75
purpose: []
